source ~/.bashrc

# my CDPATH
export CDPATH=.:~:~/Projects

# Make TextMate the default Subversion editor.  I have no idea how this works on machines without TextMate.
export EDITOR="mate -w"
export SVN_EDITOR="mate -w"
export GIT_EDITOR="mate -w"

# my PATH
export PATH="/usr/local/share/npm/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:$HOME/bin:$PATH"

# Convenience aliases
alias bp='$EDITOR ~/.bash_profile'
alias brc='$EDITOR ~/.bashrc'
alias realias='source ~/.bash_profile'
alias ll='ls -AlFT'
alias ls='/bin/ls -F'
alias flushdns='sudo dscacheutil -flushcache'
alias ffs=‘sudo !!’

# Compress the cd, ls -l series of commands.
alias lc="cl"
cl() { cd "$@" && ll; }

# git aliases
alias gs='git status'
alias gb='git branch -a --color'
alias gd='git diff --color'
alias gc='git commit -e'
alias ungit="find . -name '.git' -exec rm -rf {} \;"

# Command aliases
alias lynx='/Applications/lynx.command'
alias software_update='sudo softwareupdate -i -a'

# Generate an ssh key pair
alias keypair='ssh-keygen -t dsa'

# Automatically installs your public key to the remote host
# ssh-copy-id 'user@remotehost'

# BASH Shell configs
export HISTFILESIZE=1000000
export HISTSIZE=1000000
export HISTCONTROL=erasedups
shopt -s histappend

# Set the CLI prompt
if [ -n "$PS1" ]; then PS1='\h:\w \u\$ '; fi

# Attempt to correct mispellings of directories
shopt -s cdspell

# Allow files beginning with a dot to be returned in filename expansions
shopt -s dotglob

# Analyze my .bash_history
alias ba='cut -f1 -d" " ~/.bash_history | sort | uniq -c | sort -nr | head -n 30'

# For TimerApp
PROMPT_TITLE='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}\007"'
export PROMPT_COMMAND="${PROMPT_COMMAND} ${PROMPT_TITLE}; "

# Set up better bash completion.
# Get bash_completion here: http://www.caliban.org/bash/index.shtml#completion
if [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
fi

_mategem()
{
    local curw
    COMPREPLY=()
    curw=${COMP_WORDS[COMP_CWORD]}
    local gems="$(gem environment gemdir)/gems"
    COMPREPLY=($(compgen -W '$(ls $gems)' -- $curw));
    return 0
}

# Also set up rake task completion
complete -C ~/Dropbox/Projects/home/rakefiles/rake_completion.rb -o default rake

# Open up gem documentation in a browser.
# http://stephencelis.com/archive/2008/6/bashfully-yours-gem-shortcuts
gemdoc() {
  local gemdir=`gem env gemdir`
  open $gemdir/doc/`ls $gemdir/doc/ | grep $1 | sort | tail -1`/rdoc/index.html
}

_gemdocomplete() {
  COMPREPLY=($(compgen -W '$(ls `gem env gemdir`/doc)' -- ${COMP_WORDS[COMP_CWORD]}))
  return 0
}

complete -o default -o nospace -F _gemdocomplete gemdoc
complete -F _mategem -o dirnames mategem

function parse_git_dirty {
  if [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]]
  then
    echo "\e[0;31m"
  else
    echo "\e[0;00m"
  fi
}

#'\h:\w \u\$ '; f
PS1='\u@\h:\w$(__git_ps1 " (\[$(parse_git_dirty)\]%s\[\e[m\])") \$ '
export PS1

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

#copy output of last command to clipboard
alias cl="fc -e -|pbcopy"

# top
alias cpu='top -o cpu'
alias mem='top -o rsize' # memory

# copy the working directory path
alias cpwd='pwd|tr -d "\n"|pbcopy'

# share history between terminal sessions
alias he="history -a" # export history
alias hi="history -n" # import history

# Get your current public IP
alias ip="curl icanhazip.com"

# recursively delete Dropbox conflicted files
alias rmdbc="find . -name *\ \(*conflicted* -exec rm {} \;"

# mute the system volume
alias stfu="osascript -e 'set volume output muted true'"

# time machine log
alias tmlog="syslog -F '\$Time \$Message' -k Sender com.apple.backupd-auto -k Time ge -30m | tail -n 1"

# trim newlines
alias tn='tr -d "\n"'

# list TODO/FIX lines from the current project
alias todos="ack -n --nogroup '(TODO|FIX(ME)?):'"
