#!/usr/bin/env ruby
# 
# Copy this file into .git/hooks and chmod +x
# Acceptable branch formats will append to your message:
# AM-1234 -> AM-1234
# AM-1234_some_feature -> AM-1234 - Some Feature

require 'rubygems'
begin
  require 'git'
rescue LoadError
  puts "You must install the git gem."
  exit
end

TICKET_MATCH = /AM-[\d]+/i
repo = Git.open(".")
File.open(ARGV[0], "r+") do |file|
  if ticket = repo.current_branch.match(TICKET_MATCH)
    commit_title = repo.current_branch.split(TICKET_MATCH)[1].split("-").delete_if { |e| e.empty? }.each { |word| word.capitalize! }.join(" ") rescue nil
    message = file.read
    file.rewind
    file.puts "#{message}\n\n#{ticket[0]}#{commit_title ? " - #{commit_title}" : ""}"
  end
end

