#!/usr/bin/env ruby
# 
# Copy this file into .git/hooks and chmod +x
# Acceptable branch formats:
# VN-1234 -> VN-1234: your message
# VN-1234_some_feature -> VN-1234 - Some Feature: your message

require 'rubygems'
require 'git'

TICKET_MATCH = /VN-[\d]+/i
repo = Git.open(".")
File.open(ARGV[0], "r+") do |file|
  if ticket = repo.current_branch.match(TICKET_MATCH)
    commit_title = repo.current_branch.split(TICKET_MATCH)[1].split("_").delete_if { |e| e.empty? }.each { |word| word.capitalize! }.join(" ") rescue nil
    message = file.read
    file.rewind
    file.puts "#{ticket[0].split("_")[1]}#{commit_title ? " - #{commit_title}" : ""}: #{message}"
  end
end

